### ISSUE TITLE
config/attributes not returning correctly

### ISSUE THREAD

**Issue by ewoiset** [ait-cs-IaaS/Taranis-NG#168]
- [ ] Return on update is "None"
- [ ] Get doesn't return json
- [ ] Add tests

**Comment by not4Pedro** [comment]
here I have a question: On line [397](https://github.com/ait-cs-IaaS/Taranis-NG/pull/162/files#diff-813203484a9ea4803feaa98ac3535abbc878d59d59757c435977a4fc6c175602R397), is it an expected way to use /attributes/id, or should the request be sent to /attributes?search= --> because that search seems to use the `type` key (of the JSON). But for /attributes?search=ENUM it returns inconsistently.
Additionally, the entries created by POST, like:
```
{
        "id": 44,
        "name": "TEST Attribute name",
        "description": "Simple attribute desc TEST",
        "type": "STRING"
}
```
are actually unsearchable using the ?search=STRING.
That's actually the reason why I access it using the ID directly.

**Comment by b3n4kh** [comment]
Kamino closed and cloned this issue to [taranis-ai/taranis-ai](https://github.com/taranis-ai/taranis-ai/issues/5)
